language: ruby
cache: bundler
# we don't really need `sudo: true`, but for some reason travis docker-based systems are unreliable
# at downloading jruby, and
sudo: true
rvm:
  - 2.4.4
  - 2.5.1
  - 2.6.1
# avoid having travis install jdk on MRI builds where we don't need it.
matrix:
  include:
    - jdk: openjdk8
      rvm: jruby-9.1.17.0
    - jdk: openjdk8
      rvm: jruby-9.2.6.0
