require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  Exclude:
    - '.internal_test_app/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'lib/generators/arclight/templates/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Metrics/ModuleLength:
  Exclude:
    - 'app/helpers/arclight_helper.rb'
    - 'app/models/concerns/arclight/solr_document.rb'

Metrics/BlockLength:
  Exclude:
    - 'arclight.gemspec'
    - 'lib/arclight/traject/ead2_config.rb'
    - 'lib/tasks/**/*'
    - 'spec/features/traject/ead2_indexing_spec.rb'
    - 'spec/helpers/arclight_helper_spec.rb'
    - 'spec/features/collection_page_spec.rb'
    - 'spec/**/*'
    - 'tasks/**/*'

Metrics/LineLength:
  Max: 160

Rails:
  Enabled: true

Bundler/DuplicatedGem:
  Enabled: false

Style/FormatStringToken:
  Exclude:
    - 'spec/test_app_templates/lib/generators/test_app_generator.rb'
