development:
  startup_wait: 15
  jetty_port: 8983
  <%= ENV['TEST_JETTY_PATH'] ? "jetty_home: " + ENV['TEST_JETTY_PATH'] : '' %>

test:
  startup_wait: 15
  jetty_port: <%= ENV['TEST_JETTY_PORT'] || 8888 %>
  <%= ENV['TEST_JETTY_PATH'] ? "jetty_home: " + ENV['TEST_JETTY_PATH'] : '' %>
