require: rubocop-rspec

inherit_from:
  - .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  TargetRubyVersion: 2.3
  Exclude:
  - "lib/generators/blacklight/templates/**/*"
  - "blacklight.gemspec"

# engine_cart block includes conditional, not duplication
Bundler/DuplicatedGem:
  Exclude:
  - 'Gemfile'

# engine_cart block is following default Rails order
Bundler/OrderedGems:
  Exclude:
  - 'Gemfile'

Layout/IndentationConsistency:
  EnforcedStyle: normal

Metrics/BlockLength:
  Exclude:
    - "app/views/catalog/index.json.jbuilder"
    - "lib/railties/blacklight.rake"
    - "tasks/blacklight.rake"
    - "spec/**/*"

Metrics/ClassLength:
  Exclude:
    - "lib/blacklight/configuration.rb"

Metrics/LineLength:
  Max: 200
  Exclude:
    - 'spec/**/*'

Naming/HeredocDelimiterNaming:
  Enabled: false

Naming/PredicateName:
  NamePrefixBlacklist:
    - is_

Rails:
  Enabled: true

Rails/OutputSafety:
  Enabled: false

# https://github.com/rubocop-hq/rubocop/issues/6439
Style/AccessModifierDeclarations:
  Enabled: false

Style/MissingRespondToMissing:
  Exclude:
  - 'lib/blacklight/nested_open_struct_with_hash_access.rb'

Style/StringLiterals:
  Enabled: false
